name: Install requirements
description: Install a version of python then call pip install and report what was installed
inputs:
  python-version:
    description: Python version to install
    default: ${{ env.DEV_PYTHON }}
  pip-install:
    description: Parameters to pass to pip install
    default: "-c requirements/dev-constraints.txt -e .[dev]"

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Pip install
      run: pip install ${{ inputs.pip-install }}
      shell: bash

    - name: Report what was installed
      run: pip freeze
      shell: bash
