on:
  workflow_call:

jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python packages
        uses: ./.github/actions/install_requirements
        with:          
          python-version: ${{ env.DEV_PYTHON }}

      - name: Lint
        run: tox -e pre-commit,pyright
