name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/github-script@v7
        id: script
        if: github.event_name == 'push'
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.repo.branch}`
            })
            return prs.length > 0
    outputs:
      branch-in-pr: ${{ steps.script.outputs.result }}
  lint:
    uses: ./.github/workflows/_lint.yml

  test:
    needs: check
    if: ${{ ! needs.check.outputs.branch-in-pr }}
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        include:
          # Include one that runs in the dev environment
          - runs-on: "ubuntu-latest"
            python-version: "dev"
      fail-fast: false
    uses: ./.github/workflows/_test.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      python-version: ${{ matrix.python-version }}

  container:
    needs: check
    if: ${{ ! needs.check.outputs.branch-in-pr }}
    uses: ./.github/workflows/_container.yml
    permissions:
      packages: write

  docs:
    needs: check
    if: ${{ ! needs.check.outputs.branch-in-pr }}    
    uses: ./.github/workflows/_docs.yml

  pages:
    if: github.ref_name == 'main'
    needs: docs
    uses: ./.github/workflows/_pages.yml
    permissions:
      pages: write
      id-token: write

  dist:
    needs: check
    if: ${{ ! needs.check.outputs.branch-in-pr }}    
    uses: ./.github/workflows/_dist.yml

  pypi:
    if: github.ref_type == 'tag'
    needs: dist
    uses: ./.github/workflows/_pypi.yml
    permissions:
      id-token: write

  release:
    if: github.ref_type == 'tag'
    needs: [dist, docs]
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
