name: Docs CI

on:
  push:
  pull_request:

jobs:
  docs:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Avoid git conflicts when tag and branch pushed at same time
        if: startsWith(github.ref, 'refs/tags')
        run: sleep 60

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install system packages
        # Can delete this if you don't use graphviz in your docs
        run: sudo apt-get install graphviz

      - name: Install python packages
        uses: ./.github/actions/install_requirements
        with:
          requirements_file: requirements-dev-3.x.txt
          install_options: -e .[dev]
          artifact_name: docs

      - name: Build docs
        run: tox -e docs

      - name: Move to versioned directory
        run: mv build/html .github/pages/main

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .github/pages

      - name: Setup Pages
        uses: actions/configure-pages@v4

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write  
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
